steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/thesis-project-499512/food-images/unified-app:latest'
      - '-f'
      - 'Dockerfile.unified'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/thesis-project-499512/food-images/unified-app:latest'
timeout: '1200s'
